### ISSUE TITLE
Cannot install the package using node v16

### ISSUE THREAD

**Issue by strowk** [evanw/esbuild#1711]
I am running `npm install --save-dev esbuild` in a folder with only package.json file and getting this output: 

```
npm ERR! code 1
npm ERR! path /home/tim/testesbuild/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tim/.npm/_logs/2021-10-26T10_37_48_991Z-debug.log
```

Log file ends with following:
```
170 info run esbuild@0.13.9 postinstall node_modules/esbuild node install.js
171 info run esbuild@0.13.9 postinstall { code: 1, signal: null }
172 timing reify:rollback:createSparse Completed in 5ms
173 timing reify:rollback:retireShallow Completed in 0ms
174 timing command:install Completed in 1718ms
175 verbose stack Error: command failed
175 verbose stack     at ChildProcess.<anonymous> (/home/tim/.npm-global/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
175 verbose stack     at ChildProcess.emit (node:events:390:28)
175 verbose stack     at maybeClose (node:internal/child_process:1064:16)
175 verbose stack     at Socket.<anonymous> (node:internal/child_process:450:11)
175 verbose stack     at Socket.emit (node:events:390:28)
175 verbose stack     at Pipe.<anonymous> (node:net:687:12)
176 verbose pkgid esbuild@0.13.9
177 verbose cwd /home/tim/testesbuild
178 verbose Linux 5.11.0-34-generic
179 verbose argv "/snap/node/5510/bin/node" "/home/tim/.npm-global/bin/npm" "install" "--save-dev" "esbuild"
180 verbose node v16.12.0
181 verbose npm  v8.1.0
182 error code 1
183 error path /home/tim/testesbuild/node_modules/esbuild
184 error command failed
185 error command sh -c node install.js
186 verbose exit 1
```

I am using 
Ubuntu 20.04 
```
node --version                
v16.12.0
npm --version                 
8.1.0
```

**Comment by nozzlegear** [comment]
I'm having the same problem installing esbuild using node v16 on Ubuntu 21.04. Strangely I did not have this issue using WSL on Windows or on Mac. 

[Here's the full log file for `npm install --save-dev esbuild`](https://gist.github.com/nozzlegear/1a10b40ec3782f533347334e6f764521)

**Comment by sayful1** [comment]
I am also facing same issue.

OS: Ubuntu 20.04
npm 8.2.0
node v16.13.1

`npm install`

npm ERR! code 1
npm ERR! path /home/sayful/Downloads/vitejs-vite-uun9ga/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sayful/.npm/_logs/2021-12-22T06_00_53_027Z-debug-0.log

**Comment by evanw** [comment]
Unfortunately even that full log doesn't provide enough information. And I'm still not able to reproduce this with these instructions on my Linux VM. Here's what I tried:

```
$ mkdir test
$ cd test
$ echo {} > package.json

$ lsb_release -ds
Ubuntu 21.10

$ node --version
v16.13.1

$ npm --version
8.1.2

$ npm i esbuild@0.13.3
added 2 packages, and audited 3 packages in 2s
found 0 vulnerabilities
```

It seems to work fine. I'm going to close this issue because realistically there's nothing I'm going to be able to do about it. If someone is experiencing it themselves then it would be great if they could debug it and post here about what the problem is. If the problem is identified, then the issue can be reopened.

To debug this what you'll want to do is download the `esbuild` package from npm and extract it manually like this:

```
$ curl -O https://registry.npmjs.org/esbuild/-/esbuild-0.14.12.tgz
$ tar xf esbuild-0.14.12.tgz
$ rm esbuild-0.14.12.tgz
$ cd package
```

You can make whatever edits you want to the install script in the `package` directory (e.g. throwing an error that contains more information so it'll show up in the log) and then try out the installation to see what happens:

```
$ cd package
$ npm pack # this will generate a new esbuild-0.14.12.tgz
$ cd ..
$ mkdir demo
$ cd demo
$ npm init -y
$ npm i ../package/esbuild-0.14.12.tgz
```

**Comment by grancalavera** [comment]
Hi @evanw , thanks for suggesting a debugging approach, I have followed your instructions, and did setup the following test harness:

```
.
├── esbuild
│   ├── bin
│   │   └── esbuild
│   ├── install.js
│   ├── lib
│   │   ├── main.d.ts
│   │   └── main.js
│   ├── package.json
│   └── README.md
└── esbuild-project
    ├── node_modules
    │   └── esbuild -> ../../esbuild
    ├── package.json
    └── package-lock.json
```

Where the top level directory `esbuild` is the extracted contents of `package` in your solution, and `esbuild-project` is a test project that depends directly on the contents of `esbuild`, using `file` install paths:

```
{
  "name": "esbuild-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "esbuild": "file:../esbuild"
  }
}
```

Running `npm install` reproduces the issue in Ubuntu 20.04:
```
$ npm install
npm ERR! code 1
npm ERR! path /xxx/xxx/xxx/esbuild-issue/esbuild
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
```
Adding a node js shebang to `lib/install.js` as suggested [here](https://alexewerlof.medium.com/node-shebang-e1d4b02f731d) fixes the issue in my system:

![image](https://user-images.githubusercontent.com/301030/150678624-081a8755-6e09-4565-858e-7f484e39d1fa.png)

and:

```
$ npm install

up to date, audited 3 packages in 555ms

found 0 vulnerabilities
```

I'm not sure what are the consequences for all possible operating system, but maybe is something worth looking at.

**Comment by evanw** [comment]
That's very strange because the log line `sh -c node lib/install.js` suggests the command being run is just `node lib/install.js` which should be interpreting the file as JavaScript code, not as shell code. Do you have some strange shell installed by any chance? Or maybe you have some wrapper around the `node` command?

I can add that shebang line because it's harmless (node strips it before it runs the code). But I'm not sure that will actually fix your problem.

Side note: I believe the log line is actually `sh -c "node lib/install.js"` as a single string, which happens [here](https://github.com/npm/cli/blob/4dbeb007d0d6350284c7b1edbf4d5b0030c67c66/node_modules/%40npmcli/run-script/lib/make-spawn-args.js#L19), but the quotes around the string aren't printed for some reason.

**Comment by grancalavera** [comment]
Good observation, this is a screenshot of what I see:

![image](https://user-images.githubusercontent.com/301030/150686365-94094c76-dae1-4564-9e2d-b90e8a92b91b.png)

No quotes indeed.

From the file you linked above, it seems node determines how to run the script, and chooses to run it as `sh -c "node lib/install.js`, I can dig a little bit more.

For reference, the first thing I tried was running the script directly with node:

```
node lib/install.js
```

Which reaches the `js` script but fails for a different reason, and I would say is expected to fail since we haven't installed anything yet:

```
node install.js 
[esbuild] Failed to find package "esbuild-linux-64" on the file system

This can happen if you use the "--no-optional" flag. The "optionalDependencies"
package.json feature is used by esbuild to install the correct binary executable
for your current platform. This install script will now attempt to work around
this. If that fails, you need to remove the "--no-optional" flag to use esbuild.

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'esbuild'
```

This made me think that there's probably nothing wrong with the install script, but with the way it is executed, hence trying the first thing that came to mind which was adding a shebang...

**Comment by grancalavera** [comment]
> That's very strange because the log line sh -c node lib/install.js suggests the command being run is just node lib/install.js

I think what happens is that `npm` is handing over the postinstall script to `sh`, which then is choosing how to run it, even when we know it should run in `node`. The shebang is the hint `sh` needs to determine is ok to use `node`? Not sure, but kind of checks out?

See [this](https://askubuntu.com/a/263530):

> sh stands for "shell" and shell is the old, Unix like command line interpreter. An interpreter is an program that executes specific instructions written in a programming or scripting language. So basically you say "Execute that file for me".

**Comment by evanw** [comment]
@grancalavera The addition of the shebang line has been released in version 0.14.14: https://unpkg.com/esbuild@0.14.14/install.js. Does that fix the problem for you?

**Comment by grancalavera** [comment]
Hi @evanw, no sadly it doesn't work. I'm sure I made a mistake while testing during the weekend. I wrote a little test harness and now I can make it fail consistently:

```shell
VERSION=0.14.14

rm -rf esbuild project

curl -O https://registry.npmjs.org/esbuild/-/esbuild-"${VERSION}".tgz
tar xf esbuild-"${VERSION}".tgz
rm esbuild-"${VERSION}".tgz
mv package esbuild

mkdir project
cd project
npm init -y
npm install ../esbuild
```

That fails the same way as before:

```
$ ./install-from-tgz.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24431  100 24431    0     0  50686      0 --:--:-- --:--:-- --:--:-- 50686
Wrote to esbuild-issue/project/package.json:

{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm ERR! code 1
npm ERR! path esbuild-issue/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!npm/_logs/2022-01-27T20_51_15_793Z-debug-0.log
```

I'll look into it a bit more.

**Comment by evanw** [comment]
There's a report that using node 17.4 fixes this issue: https://github.com/evanw/esbuild/issues/1973#issuecomment-1025149179. If someone who is able to reproduce this issue has the time to debug this, it would still be very useful to understand how far the install script gets before it fails and what's causing it to fail.

**Comment by JamesBoon** [comment]
Hi, I got the same error on my machine.

```
Ubuntu 18.04
node 16.13.2 (installed via snap)
npm 8.4.0
```

I used the script by @grancalavera to have full control over the installed esbuild version. I just changed the install command to this:
```
npm install ../esbuild --no-progress --foreground-scripts --loglevel silly 2>&1 | tee
```
This helps to see all messages from the `postinstall` script. The `tee` hack works around a current npm bug which ignores the `no-progress` flag.

I added some more logging and the error seems to be caused by [this line](https://github.com/evanw/esbuild/blob/v0.14.14/lib/npm/node-platform.ts#L57), where `require.resolve('esbuild')` seems to throw.

Comparing the log results, it is the exact same error which I would get when calling `node install.js` directly from within the `esbuild` folder.

I hope this helps.

**Comment by JamesBoon** [comment]
Replacing each line of `path.dirname(require.resolve('esbuild'));` with a call to this helper function fixed the issue for me:
```
function getEsbuildLibDir() {   
  try {
      return path.dirname(require.resolve("esbuild"));
  } catch {
      // as "install.js" is always inside the esbuild folder, this should be ok as fallback
      return __dirname; // or better process.cwd()?
  }
}
```
Some notes to reproduce this issue: 
- no `node_modules` folder should be present in the target folder
- no `package-lock.json` should be present in the target folder
- it works if called via yarn 1 

@evanw, what do you think? Is this fix ok? Should I open a PR?

**Comment by evanw** [comment]
Thanks for the research. This is valuable progress!

I do still wonder what's actually going on though (why `require.resolve` doesn't work on certain people's machines). Maybe snap-installed node is part of the problem? Ideally we'd be able to figure out why it's happening because esbuild's install script also needs to call `require.resolve` on packages other than itself and I suspect it can't always rely on being able to do e.g. `__dirname + '/../esbuild-linux-64'` to find other packages since npm sometimes installs other packages in random other places instead.

**Comment by evanw** [comment]
I was finally able to reproduce this issue in a new VM. I had to install node via snap instead of downloading the official version to reproduce the issue.

But when I debug the failure in my VM, I confusingly narrowed the issue down to the fact that stdout and stderr aren't writable? I tried an install script only containing one line that writes to stdout in a few different ways:

```js
// This "install.js" file installs fine
console.log('test');
```

```js
// This "install.js" file throws "Error: EACCES: permission denied, write"
process.stdout.write('test\n');
```

```js
// This "install.js" file also throws "Error: EACCES: permission denied, write"
require('fs').writeSync(1, 'test\n');
```

I don't understand why this is happening or why `console.log` works while the others don't. Maybe `console.log` is buffered somehow? I have no idea how it works under the hood.

These test cases were reduced down from the original problem which was that `require('child_process').execFileSync('esbuild', ['--version'])` crashed with `EACCES: permission denied, write`. This was in the install verification step, which is the last step (the package appears to have been installed fine on my machine only to fail on the verification step).

I seem to be able to fix that problem by adding `{ stdio: 'pipe' }` to the call to `execFileSync`. The documentation for `execFileSync` says this about the `stdio` option:

> `stdio` \<string\> | \<Array\> Child's stdio configuration. `stderr` by default will be output to the parent process' stderr unless `stdio` is specified. **Default:** `'pipe'`.

So maybe the underlying issue here is that when node is installed via snap, stderr is somehow not writable from install scripts?

**Comment by evanw** [comment]
I just released version 0.14.17 with my fix described above and I have verified that it fixes the issue for me. I can no longer reproduce the issue in my VM with the latest version of esbuild. Any chance that fixes esbuild installation for anyone who couldn't install esbuild before?

**Comment by JamesBoon** [comment]
Hi @evanw, I'm super sorry, but double checking my test-setup I found out I was actually debugging an error caused by the test setup itself. :facepalm:

Re-running each former failing `npm install` suddenly works - even with older versions. :face_with_spiral_eyes: 
Could this be, that it was a temporary problem with npm? Something related to downloading the binaries?

**Comment by yabuking84** [comment]
I just had this error when using Snap NodeJS, but no issues when using NodeSource NodeJS.

**Comment by JamesBoon** [comment]
@yabuking84 did you try the latest esbuild release? did this fix the issue?

**Comment by hpx7** [comment]
I'm seeing still issues on Ubuntu, using node install with nvm

`npm i esbuild` works, but installing globally via `npm i -g esbuild` fails with:
```
error code 1
error path /root/.nvm/versions/node/v16.13.2/lib/node_modules/esbuild
error command failed
error command sh -c node install.js
error node:internal/modules/cjs/loader:930
error   throw err;
error   ^
error
error Error: Cannot find module '/root/.nvm/versions/node/v16.13.2/lib/node_modules/esbuild/install.js'
error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
error     at Function.Module._load (node:internal/modules/cjs/loader:772:27)
error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
error     at node:internal/main/run_main_module:17:47 {
error   code: 'MODULE_NOT_FOUND',
error   requireStack: []
error }
```

**Comment by evanw** [comment]
It looks like it’s saying it can’t even find the install script in the first place? That’s a problem with npm/node, not with esbuild. The install script is published in that location as part of the esbuild package.

**Comment by yabuking84** [comment]
> 

I didnt yet, I didnt use Snapcraft package manager, I just used NodeSource's install script. Ill try to install latest esbuild release using Snapcraft's package manager.

**Comment by yabuking84** [comment]
> I didnt yet, I didnt use Snapcraft package manager, I just used NodeSource's install script. Ill try to install latest esbuild release using Snapcraft's package manager.

**Comment by strowk** [comment]
I can confirm that change from
>  "esbuild": "^0.13.0",
to 
> "esbuild": "^0.14.17",
fixes the issue I initially described

Thanks for the fix! 
Sorry I only now noticed this is fixed

**Comment by david-commit** [comment]
> I'm having the same problem installing esbuild using node v16 on Ubuntu 21.04. Strangely I did not have this issue using WSL on Windows or on Mac.
> 
> [Here's the full log file for `npm install --save-dev esbuild`](https://gist.github.com/nozzlegear/1a10b40ec3782f533347334e6f764521)
> 
> Edit: ignoring the postinstall script (`npm install --save-dev --ignore-scripts esbuild`) got it installed and esbuild seems to be building my project without issue.

This solved my issue running `npm install` on a Vite app. Deleted the directory and generated a new one. Thanks!

**Comment by airtonix** [comment]
@evanw it's worth mentioning that if you're 

> > That's very strange because the log line sh -c node lib/install.js suggests the command being run is just node lib/install.js
> 
> I think what happens is that `npm` is handing over the postinstall script to `sh`, which then is choosing how to run it, even when we know it should run in `node`. The shebang is the hint `sh` needs to determine is ok to use `node`? Not sure, but kind of checks out?
> 
> See [this](https://askubuntu.com/a/263530):
> 
> > sh stands for "shell" and shell is the old, Unix like command line interpreter. An interpreter is an program that executes specific instructions written in a programming or scripting language. So basically you say "Execute that file for me".

`sh` also doesn't load any `profile`/`*rc`, so if you're relying on that to get things sane... then just dont rely on `sh` doing anything for you here.
This is one of many reasons why the `env` interpretor exists.

**Comment by Monariih** [comment]
I had the same issue in UBUNTU 23.04 then i  run npm i esbuild and it worked

**Comment by zwq-88** [comment]
/home/keqing/Mocap-Drones/computer_code/node_modules/esbuild/install.js:117
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by evanw** [comment]
Optional catch bindings are [supported in node ≥10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#browser_compatibility), and [esbuild requires node ≥12](https://github.com/evanw/esbuild/blob/bfe6f5142ad9756fd7b4430541b9d9265d879b26/npm/esbuild/package.json#L15). So `} catch {` shouldn't be a syntax error as long as you are using a supported version of node. If that happens because you're using a really old version of node, then you should update to a newer version of node.

**Comment by zwq-88** [comment]
Thanks for the reply, after I upgraded nodejs to v16, yarn install passed!
&nbsp;


Am
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Evan ***@***.***&gt;; 
发送时间: 2024年4月3日(星期三) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [evanw/esbuild] Cannot install the package using node v16 (Issue #1711)














 
Optional catch bindings are supported in node ≥10, and esbuild requires node ≥12. So } catch { shouldn't be a syntax error as long as you are using a supported version of node. If that happens because you're using a really old version of node, then you should update to a newer version of node.
