### ISSUE TITLE
Unable to install v0.19.2

### ISSUE THREAD

**Issue by asportnoy** [evanw/esbuild#3347]
I was able to update ESBuild to v0.18.x in our repository, but attempting to install v0.19.x gives the following error:

```
node_modules/.pnpm/esbuild@0.19.2/node_modules/esbuild: Running postinstall script, failed in 58ms
.../esbuild@0.19.2/node_modules/esbuild postinstall$ node install.js
│ node:internal/modules/cjs/loader:998
│   throw err;
│   ^
│ Error: Cannot find module '/Users/albert/Programming/Discord/replugged/node_modules/.pnpm/esbuild@0.19.2/node_modules/esbuild/i…
│     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
│     at Module._load (node:internal/modules/cjs/loader:841:27)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
│     at node:internal/main/run_main_module:23:47 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: []
│ }
│ Node.js v18.12.1
└─ Failed in 58ms at /Users/albert/Programming/Discord/replugged/node_modules/.pnpm/esbuild@0.19.2/node_modules/esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

 Repository: https://github.com/replugged-org/replugged. Check out the `esbuild-updates` branch since that works with `>=0.17`. We use `pnpm` so you may need to use that to test in order to reproduce, not sure.

1) `pnpm i`, verify that it installs successfully.
2) `pnpm i esbuild@0.19`, verify that it fails with the above error.

**Comment by hyrious** [comment]
I cannot reproduce your error with your repo. The error says it cannot find
node_modules/.pnpm/esbuild@0.19.2/node_modules/esbuild/install.js, however that file exists on my FS and the update succeeded.

FYI, I ran this command to update esbuild:

```console
$ pnpm -v
8.7.0

$ pnpm up -L esbuild
```

**Comment by asportnoy** [comment]
Just tried it again and now it works 🤦‍♂️ no clue what changed in the last 9 hours but it works so 🤷‍♂️
