### PR TITLE
Update golang.org/x/sys v0.1.0 for CWE-266

### PR DESCRIPTION
**Pull request by madhavajay**
As per this PR:
https://github.com/evanw/esbuild/pull/3248

The minimum version that fixes the CWE is v0.1.0, will that work with the old version you are using?

https://pkg.go.dev/golang.org/x/sys?tab=versions
Screenshot 2023-07-20 at 12 56 58 pm

### CODE REVIEW

**Comment by evanw** [comment]
This doesn't work either:

```
go: downloading golang.org/x/sys v0.1.0
go: extracting golang.org/x/sys v0.1.0
go: finding golang.org/x/sys v0.1.0
# golang.org/x/sys/unix
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_linux.go:2255:9: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
Error: Process completed with exit code 2.
```

That version requires Go 1.17, so it doesn't work with Go 1.13.

**Comment by madhavajay** [comment]
Hrm, that is certainly disappointing. I guess this problem will occur eventually.
Screenshot 2023-07-21 at 10 57 39 am

Feel free to close.
