### ISSUE TITLE
[bug] "Transforming destructuring is not supported yet" since 0.9.3

### ISSUE THREAD

**Issue by jurijzahn8019** [evanw/esbuild#988]
Hi,

since 0.9.3 i get this error. Works in 0.9.2

```plaintext
> vite -c vite.config.ts build

vite v2.1.1 building for production...
✓ 114 modules transformed.
error during build:
Error: Transform failed with 4 errors:
assets/index.5b8f7deb.js:4:6: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.5b8f7deb.js:6:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.5b8f7deb.js:7:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.5b8f7deb.js:15:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
    at failureErrorWithLog ( <root_dir>/node_modules/esbuild/lib/main.js:1195:15)
    at <root_dir>/node_modules/esbuild/lib/main.js:1056:33
    at <root_dir>/node_modules/esbuild/lib/main.js:566:9
    at handleIncomingPacket ( <root_dir>/node_modules/esbuild/lib/main.js:655:9)
    at Socket.readFromStdout ( <root_dir>/node_modules/esbuild/lib/main.js:533:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by zhangshuaidan** [comment]
I meet the same error, here is detail info
`assets/vendor.93f489e5.js:629:22: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
...
    at failureErrorWithLog (D:\dev\vue\vite-project\node_modules\esbuild\lib\main.js:1195:15)
    at D:\dev\vue\vite-project\node_modules\esbuild\lib\main.js:1056:33
    at D:\dev\vue\vite-project\node_modules\esbuild\lib\main.js:566:9
    at handleIncomingPacket (D:\dev\vue\vite-project\node_modules\esbuild\lib\main.js:655:9)
    at Socket.readFromStdout (D:\dev\vue\vite-project\node_modules\esbuild\lib\main.js:533:7)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by jurijzahn8019** [comment]
I have created a reproduction

[esbuild_test.tar.gz](https://github.com/evanw/esbuild/files/6156584/esbuild_test.tar.gz)

**Comment by fabd** [comment]
Me too. I thought at first it was my `browserslist` in package.json, but removing it doesn't fix the issue.

Environment : a recent `yarn upgrade --latest` of a `vue-ts` app created with **vite**.

**Comment by fabd** [comment]
For now this seems to work:

```sh
yarn remove vite
yarn add vite@2.0.5
```

`yarn why esbuild` ... `Found "esbuild@0.8.57"`

**Comment by MatejBransky** [comment]
Here is my workaround:

`package.json`:
```
{
  "resolutions": {
    "esbuild": "0.9.2"
  }
}
```

and then run:
```
yarn
```

**Comment by evanw** [comment]
This is happening because of a recent change to fix how esbuild determines browser feature compatibility. From the release notes for version 0.9.3:

> * Raise certain VM versions in the JavaScript feature compatibility table
>
>     JavaScript VM feature compatibility data is derived from this dataset: https://kangax.github.io/compat-table/. The scripts that process the dataset expand the data to include all VM versions that support a given feature (e.g. chrome44, chrome45, chrome46, ...) so esbuild takes the minimum observed version as the first version for which the feature is supported.
>
>     However, some features can have subtests that each check a different aspect of the feature. In this case the desired version is the minimum version within each individual subtest, but the maximum of those versions across all subtests (since esbuild should only use the feature if it works in all cases). Previously esbuild computed the minimum version across all subtests, but now esbuild computes the maximum version across all subtests. This means esbuild will now lower JavaScript syntax in more cases.

One of the tests causing this is called `destructuring, parameters: shorthand defaults, arrow function` and looks like this:

```js
return ((a, {b = 0, c = 3}) => {
  return a === 1 && b === 2 && c === 3;
})(1, {b: 2});
```

The compatibility data says this:

```js
edge15: false,
edge18: true,
```

So according to this, destructuring doesn't fully work correctly until Edge 18 and allowing destructuring syntax with Edge <18 is potentially dangerous. What esbuild was doing previously was incorrect and could cause bugs.

The most straightforward fix to this issue is to update your esbuild configuration to use a target of `edge18` or higher. This seems very reasonable to me as [the legacy version of Microsoft Edge is no longer supported by Microsoft](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge):

> End of support for the legacy version of the Microsoft Edge desktop app is on March 9, 2021. This means that Microsoft Edge Legacy will not receive security updates after that date. Go [here](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224) to learn more.

If you follow that link, it says that Microsoft will soon be actively removing these old versions of Edge with an automatic update:

> To replace this out of support application, we are announcing that the new Microsoft Edge will be available as part of the Windows 10 cumulative monthly security update—otherwise referred to as the Update Tuesday (or “B”) release—on April 13, 2021. When you apply this update to your devices, the out of support Microsoft Edge Legacy desktop application will be removed and the new Microsoft Edge will be installed.

This seems like something that needs to be fixed on the Vite side to me.

**Comment by evanw** [comment]
Update: It sounds like this has been fixed in [Vite version 2.1.2](https://github.com/vitejs/vite/blob/bc35fe994d48b2bd7076474f4a1a7b8ae5e8f401/packages/vite/CHANGELOG.md#212-2021-03-17).

**Comment by jurijzahn8019** [comment]
Thank you very much for the explanation. Then I will look forward to Vite update.
